---
- hosts: all
  sudo: yes

  tasks:
    - name: update apt repo
      apt: update-cache=yes

    - name: install git
      apt: name={{item}} state=installed
      with_items:
        - git
        - supervisor
        - golang

    - name: get the git project
      git: repo=https://bitbucket.org/resmio/imgresize.git dest={{project_dir}}

    - name: get the go dependencies
      command: go get github.com/nfnt/resize

    - name: build the go project
      command: chdir={{project_dir}} go build

    - name: create cache directory
      command: mkdir -p {{project_dir}}/cachedir/

    - name: give access to cachedirectory
      command: chown www-data {{project_dir}}/cachedir/

    - name: copy supervisor configuration file
      template: src=./files/supervisord.conf dest=/etc/supervisor/conf.d/imgresize.conf

    - name: restart supervisor
      service: name=supervisor state=restarted