---
- hosts: all
  sudo: yes

  tasks:
    - name: update apt repo
      action: apt update-cache=yes

    - name: update AUFS filesystem support
      # sudo apt-get install linux-image-extra-`uname -r`
      action: apt name=linux-image-extra-3.8.0-31-generic state=installed

    - name: add the docker repository key to your local keychain
      action: apt_key url=https://get.docker.io/gpg state=present

    - name: add the docker repository to your apt sources list
      action: apt_repository repo='deb http://get.docker.io/ubuntu docker main' state=present

    - name: update apt repo
      action: apt update-cache=yes

    - name: install docker
      action: apt name=lxc-docker state=installed

    - name: Build docker image
      command: docker build -t /imgresize /vagrant